"""Module C — the physician-ready history.

Assembled from templates, not generated by a model. The section order is fixed by the
brief and reproduced exactly:

    Chief complaint -> HPI -> Past medical/surgical -> Drug & allergy -> Family
    -> Personal -> Review of systems -> Prior investigations

A model may be asked to smooth the HPI paragraph into readable prose, and that is the
only place one is allowed near this file. It is given the structured facts and told it
may not add to them; if it is unreachable, or if it returns anything that fails the
check below, the deterministic sentence is used instead. The summary therefore always
exists, always says the same things, and never contains a symptom the patient did not
report.

**This is a history, not an impression.** Nothing in this module names a disease,
ranks a differential, or suggests a next step. Hard rule 1, and the brief's own
words: "a draft to accept, amend, or reject, never an autonomous diagnosis."
"""

from __future__ import annotations

from typing import Any

from . import llm
from .engine import Session
from .ontology import Ontology

# Human-readable renderings for slot values. The ontology stores machine values and
# the screen labels are written for patients ("Sweet — rice, milk, sugar"); a doctor
# reading 400 of these a week needs the clinical word instead.
CLINICAL_TERMS: dict[str, str] = {
    # onset / character / timing
    "sudden": "sudden onset", "gradual": "gradual onset",
    "burning": "burning", "dull_ache": "dull ache", "sharp_stabbing": "sharp, stabbing",
    "cramping": "cramping", "throbbing": "throbbing", "pressure_heavy": "heavy, pressure-like",
    "tingling": "tingling",
    "constant": "constant", "comes_and_goes": "intermittent",
    "worse_morning": "worse in the mornings", "worse_night": "worse at night",
    "worse_after_food": "worse after food", "worse_empty_stomach": "worse on an empty stomach",
    "unrelated": "no clear pattern",
    "getting_worse": "progressively worsening", "getting_better": "improving",
    "same": "unchanged", "fluctuating": "fluctuating",
    # sites
    "upper_abdomen": "upper abdomen", "lower_abdomen": "lower abdomen",
    "whole_abdomen": "generalised abdominal", "central_chest": "central chest",
    "left_chest": "left chest", "right_chest": "right chest",
    "forehead": "frontal", "back_of_head": "occipital", "one_side_head": "unilateral",
    "whole_head": "generalised", "knee": "knee", "shoulder": "shoulder",
    "lower_back": "lower back", "neck": "neck", "hip": "hip",
    "multiple_joints": "multiple joints", "other_site": "other site",
    # radiation
    "none": "none", "to_back": "to the back", "to_left_arm": "to the left arm",
    "to_jaw": "to the jaw/neck", "to_shoulder": "to the shoulder",
    "to_groin": "to the groin", "to_leg": "down the leg", "elsewhere": "elsewhere",
    # associated / ROS
    "nausea": "nausea", "vomiting": "vomiting", "fever": "fever", "sweating": "diaphoresis",
    "dizziness": "giddiness", "breathlessness": "breathlessness",
    "palpitations": "palpitations", "loose_motion": "loose stools",
    "constipation": "constipation", "weight_loss": "weight loss",
    "appetite_loss": "anorexia", "night_sweats": "night sweats", "fatigue": "fatigue",
    "weight_gain": "weight gain", "chest_pain": "chest pain", "cough": "cough",
    "blood_in_sputum": "haemoptysis", "ankle_swelling": "ankle oedema",
    "abdominal_pain": "abdominal pain", "blood_in_stool": "blood per rectum",
    "black_stool": "melaena", "jaundice": "jaundice",
    "difficulty_swallowing": "dysphagia", "headache": "headache",
    "giddiness": "giddiness", "fainting": "syncope", "numbness": "paraesthesia",
    "weakness_limb": "limb weakness", "vision_change": "visual disturbance",
    "fits": "seizures", "burning_urine": "dysuria", "blood_in_urine": "haematuria",
    "frequency": "urinary frequency", "retention": "urinary retention",
    # past / drugs
    "diabetes": "diabetes mellitus", "hypertension": "hypertension",
    "heart_disease": "cardiac disease", "asthma": "asthma",
    "tuberculosis": "tuberculosis", "thyroid": "thyroid disorder",
    "kidney_disease": "renal disease", "liver_disease": "hepatic disease",
    "stroke": "cerebrovascular accident", "cancer": "malignancy",
    "epilepsy": "epilepsy", "arthritis": "arthritis", "unsure": "patient unsure",
    "mental_illness": "psychiatric illness",
    "allopathic": "allopathic", "ayurvedic": "Ayurvedic", "homeopathic": "homeopathic",
    "siddha": "Siddha", "unani": "Unani", "self_medication": "self-medication",
    "regular": "regular", "sometimes_missed": "intermittently missed",
    "stopped": "discontinued",
    "drug_allergy": "drug reaction", "food_allergy": "food reaction",
    "both": "drug and food reactions",
    "never": "never", "within_year": "within the last year",
    "one_to_five_years": "1-5 years ago", "over_five_years": "over 5 years ago",
    # personal
    "vegetarian": "vegetarian", "non_vegetarian": "non-vegetarian",
    "eggetarian": "vegetarian with eggs", "vegan": "vegan",
    "chewing": "chewed tobacco", "smoking": "smoking", "quit": "former use",
    "occasional": "occasional", "good": "good",
    "difficulty_falling": "delayed sleep onset", "waking_often": "frequent waking",
    "too_little": "insufficient", "too_much": "excessive",
    "constipated": "constipated", "loose": "loose", "alternating": "alternating",
    "sedentary": "sedentary", "standing_long": "prolonged standing",
    "heavy_physical": "heavy physical labour", "night_shift": "night shifts",
    "not_working": "not currently working",
    "irregular": "irregular", "painful": "dysmenorrhoea", "heavy": "menorrhagia",
    "not_applicable": "declined",
    # AYUSH
    "pravara": "Pravara (superior)", "madhyama": "Madhyama (moderate)",
    "avara": "Avara (inferior)", "unassessed": "not assessed",
    "compact_strong": "compact, firm", "moderate": "moderate", "loose_weak": "loose, slack",
    "proportionate": "proportionate", "above_proportion": "above proportion",
    "below_proportion": "below proportion",
    "adapts_easily": "adapts easily", "adapts_moderately": "adapts moderately",
    "adapts_poorly": "adapts poorly",
    "good_intake_good_digestion": "adequate intake, adequate digestion",
    "good_intake_poor_digestion": "adequate intake, impaired digestion",
    "poor_intake_good_digestion": "reduced intake, adequate digestion",
    "poor_intake_poor_digestion": "reduced intake, impaired digestion",
    "high": "high", "low": "low", "cannot_exert": "unable to exert",
    "bala": "Bala (childhood)", "madhya": "Madhya (middle)", "vriddha": "Vriddha (elderly)",
    "sama": "Sama (regular)", "vishama": "Vishama (irregular)",
    "tikshna": "Tikshna (sharp)", "manda": "Manda (weak)",
    "mridu": "Mridu (soft)", "krura": "Krura (hard)",
    "vata_aggravated": "Vata aggravation", "pitta_aggravated": "Pitta aggravation",
    "kapha_aggravated": "Kapha aggravation", "unclear": "no clear change reported",
    "regular_times": "regular meal times", "skips_meals": "skips meals",
    "madhura": "Madhura (sweet)", "amla": "Amla (sour)", "lavana": "Lavana (salty)",
    "katu": "Katu (pungent)", "tikta": "Tikta (bitter)", "kashaya": "Kashaya (astringent)",
    "light": "light", "early_to_bed": "early to bed", "late_night": "late nights",
    "day_sleeping": "daytime sleeping (divasvapna)",
    # ages
    "under_18": "under 18", "18_39": "18-39", "40_59": "40-59",
    "60_74": "60-74", "75_plus": "75+",
    "female": "female", "male": "male", "other": "other", "declined": "not stated",
    "self": "the patient", "relative": "a family member", "attendant": "an attendant",
}

DOSHA_OF = {
    "vata_lean_dry_restless": "Vata", "vata_variable_appetite": "Vata", "vata_light_sleep": "Vata",
    "pitta_sharp_appetite": "Pitta", "pitta_warm_intolerant": "Pitta", "pitta_irritable": "Pitta",
    "kapha_heavy_build": "Kapha", "kapha_slow_digestion": "Kapha", "kapha_deep_sleep": "Kapha",
}


def term(value: Any) -> str:
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, list):
        return ", ".join(term(v) for v in value) or "none"
    if isinstance(value, dict) and "n" in value:
        n, unit = value["n"], value["unit"]
        return f"{n} {unit[:-1] if n == 1 else unit}"
    return CLINICAL_TERMS.get(str(value), str(value).replace("_", " "))


def _get(session: Session, slot: str) -> Any:
    value = session.slots.get(slot)
    return None if value in (None, [], "") else value


def _proxy_note(session: Session) -> str | None:
    """Requirement R1. A history given by someone else is a different clinical fact,
    and the doctor has to see that before reading a word of it."""
    respondent = session.slots.get("identity.respondent")
    if respondent and respondent != "self":
        return f"History given by {term(respondent)}, not the patient."
    return None


# ---------------------------------------------------------------- HPI prose

_HPI_SYSTEM = (
    "You turn structured intake fields into ONE short clinical sentence for a busy "
    "physician.\n"
    "Absolute rules:\n"
    "1. Use ONLY the facts given. Adding anything not listed is a serious error.\n"
    "2. Never name, suggest, or imply a diagnosis. You are writing a history.\n"
    "3. One or two sentences, under 45 words, plain clinical English.\n"
    "4. No preamble, no heading. Output the sentence only."
)


def _hpi_deterministic(session: Session) -> str:
    """The sentence that is always available, with or without a model."""
    bits = []
    site = _get(session, "hpi.site")
    character = _get(session, "hpi.character")
    complaint = _get(session, "cc.primary")
    duration = _get(session, "hpi.duration")

    lead = term(complaint) if complaint else "Presenting complaint"
    if site:
        lead = f"{term(site).capitalize()} {('pain' if 'pain' in str(complaint) else str(term(complaint)))}"
    if character:
        lead += f", {term(character)} in character"
    if duration:
        lead += f", for {term(duration)}"
    bits.append(lead)

    onset = _get(session, "hpi.onset")
    if onset and onset != "unsure":
        bits.append(term(onset))
    radiation = _get(session, "hpi.radiation")
    if radiation and radiation != "none":
        bits.append(f"radiating {term(radiation)}")
    timing = _get(session, "hpi.timing")
    if timing:
        bits.append(term(timing))
    severity = _get(session, "hpi.severity")
    if severity is not None:
        bits.append(f"severity {severity}/10")
    progression = _get(session, "hpi.progression")
    if progression:
        bits.append(term(progression))

    sentence = "; ".join(bits) + "."

    associated = _get(session, "hpi.associated")
    if associated and associated != ["none"]:
        sentence += f" Associated with {term([a for a in associated if a != 'none'])}."
    aggravating = _get(session, "hpi.aggravating")
    relieving = _get(session, "hpi.relieving")
    if aggravating and aggravating != ["nothing_particular"]:
        sentence += f" Worse with {term([a for a in aggravating if a != 'nothing_particular'])}."
    if relieving and relieving != ["nothing_helps"]:
        sentence += f" Relieved by {term([r for r in relieving if r != 'nothing_helps'])}."
    elif relieving == ["nothing_helps"]:
        sentence += " No relieving factor reported."

    first = _get(session, "hpi.first_episode")
    if first is False:
        sentence += " Not the first episode."
    return sentence


def _no_new_symptoms(text: str, facts: str) -> bool:
    """Reject a rewrite that smuggled in a word the facts never contained.

    Crude on purpose. It cannot catch every fabrication, but it catches the failure
    mode that matters — a model helpfully adding 'radiating to the left arm' — and it
    fails closed to the deterministic sentence, which is never wrong.
    """
    risky = {
        "radiat", "diagnos", "likely", "suggest", "consistent with", "rule out",
        "probable", "impression", "differential", "recommend", "advise", "should",
    }
    lowered = text.lower()
    facts_lower = facts.lower()
    return not any(word in lowered and word not in facts_lower for word in risky)


def hpi_paragraph(session: Session, *, use_llm: bool = True) -> tuple[str, str]:
    """Returns (paragraph, how) where how is 'template' or a provider name."""
    baseline = _hpi_deterministic(session)
    if not use_llm:
        return baseline, "template"

    facts = "\n".join(
        f"- {slot}: {term(value)}"
        for slot, value in session.slots.items()
        if slot.startswith(("cc.", "hpi.")) and value not in (None, [], "")
    )
    parsed = llm.chat(
        [
            {"role": "system", "content": _HPI_SYSTEM},
            {"role": "user", "content": f"Facts:\n{facts}\n\nWrite the sentence."},
        ],
        temperature=0.1,
    )
    if parsed.ok and parsed.text.strip():
        candidate = parsed.text.strip().strip('"')
        if len(candidate) < 400 and _no_new_symptoms(candidate, facts + baseline):
            return candidate, parsed.provider
    return baseline, "template"


# ---------------------------------------------------------------- assembly


def build(
    ont: Ontology,
    session: Session,
    timeline: dict[str, Any] | None = None,
    *,
    use_llm: bool = True,
) -> dict[str, Any]:
    """The whole summary, in the brief's section order."""
    from .engine import coverage  # local import keeps engine.py free of this module

    paragraph, how = hpi_paragraph(session, use_llm=use_llm)
    sections: list[dict[str, Any]] = []

    def add(key: str, title: str, lines: list[str], note: str | None = None) -> None:
        sections.append(
            {"key": key, "title": title, "lines": [l for l in lines if l], "note": note}
        )

    # 1 — Chief complaint
    complaint_lines = []
    if _get(session, "cc.primary"):
        complaint_lines.append(term(session.slots["cc.primary"]).capitalize())
    if _get(session, "hpi.duration"):
        complaint_lines[-1] = f"{complaint_lines[-1]} for {term(session.slots['hpi.duration'])}"
    narration = _get(session, "cc.narration")
    add(
        "cc",
        "Chief complaint",
        complaint_lines,
        note=f'In the patient\'s own words: "{narration}"' if narration else None,
    )

    # 2 — HPI
    add("hpi", "History of present illness", [paragraph])

    # 3 — Past medical and surgical
    past = []
    conditions = _get(session, "past.conditions")
    if conditions:
        past.append(
            "Known: " + term([c for c in conditions if c != "none"])
            if conditions != ["none"]
            else "No known chronic illness"
        )
    if _get(session, "past.surgeries") is True:
        detail = _get(session, "past.surgeries_detail")
        past.append(f"Previous surgery: {detail}" if detail else "Previous surgery (details not given)")
    elif session.slots.get("past.surgeries") is False:
        past.append("No previous surgery")
    if _get(session, "past.hospitalisation"):
        past.append(f"Last admission: {term(session.slots['past.hospitalisation'])}")
    add("past", "Past medical & surgical history", past)

    # 4 — Drug and allergy
    drugs = []
    if session.slots.get("drugs.taking_now") is True:
        systems = [s for s in (_get(session, "drugs.systems") or []) if s != "none"]
        line = "Currently on medication"
        if systems:
            line += f" ({term(systems)})"
        if _get(session, "drugs.adherence"):
            line += f", adherence {term(session.slots['drugs.adherence'])}"
        drugs.append(line)
    elif session.slots.get("drugs.taking_now") is False:
        drugs.append("Not on any medication")
    allergy = _get(session, "drugs.allergy_known")
    if allergy == "none":
        drugs.append("No known allergies")
    elif allergy:
        detail = _get(session, "drugs.allergy_detail")
        drugs.append(f"ALLERGY: {term(allergy)}" + (f" — {detail}" if detail else ""))
    add("drugs", "Drug & allergy history", drugs)

    # 5 — Family
    family = _get(session, "family.conditions")
    add(
        "family",
        "Family history",
        [
            "No relevant family history"
            if family == ["none"]
            else (f"Family history of {term([f for f in family if f != 'none'])}" if family else "")
        ],
    )

    # 6 — Personal
    personal = []
    for slot, label in [
        ("personal.diet", "Diet"), ("personal.tobacco", "Tobacco"),
        ("personal.alcohol", "Alcohol"), ("personal.sleep", "Sleep"),
        ("personal.bowel", "Bowels"), ("personal.occupation_strain", "Occupation"),
        ("personal.menstrual", "Menstrual"),
    ]:
        if _get(session, slot):
            personal.append(f"{label}: {term(session.slots[slot])}")
    add("personal", "Personal history", personal)

    # 7 — Review of systems
    ros = []
    danger = _get(session, "ros.danger_signs")
    if danger and danger != ["none"]:
        ros.append("DANGER SIGNS REPORTED: " + term([d for d in danger if d != "none"]))
    elif danger == ["none"]:
        ros.append("Danger-sign screen negative")
    for slot, label in [
        ("ros.general", "General"), ("ros.cardioresp", "Cardiorespiratory"),
        ("ros.gi", "Gastrointestinal"), ("ros.neuro", "Neurological"),
        ("ros.uro", "Genitourinary"),
    ]:
        value = _get(session, slot)
        if value and value != ["none"]:
            ros.append(f"{label}: {term([v for v in value if v != 'none'])}")
    if not any(l.startswith(("General", "Cardio", "Gastro", "Neuro", "Genito")) for l in ros):
        ros.append("Systems review not reached within the interview budget")
    add("ros", "Review of systems", ros)

    # 8 — AYUSH. Placed after the mandated core sections so the standard history is
    # never displaced, and rendered with its provenance attached.
    if session.mode == "ayush":
        ayush = []
        prakriti = _get(session, "ayush.prakriti_screen")
        if prakriti:
            counts: dict[str, int] = {}
            for item in prakriti:
                dosha = DOSHA_OF.get(item)
                if dosha:
                    counts[dosha] = counts.get(dosha, 0) + 1
            if counts:
                ranked = sorted(counts.items(), key=lambda kv: -kv[1])
                ayush.append(
                    "Prakriti screen (abbreviated, patient-reported): "
                    + ", ".join(f"{d} {n}/3" for d, n in ranked)
                )
        for slot, label in [
            ("ayush.vikriti", "Vikriti"), ("ayush.sara", "Sara"),
            ("ayush.samhanana", "Samhanana"), ("ayush.pramana", "Pramana"),
            ("ayush.satmya", "Satmya"), ("ayush.sattva", "Sattva"),
            ("ayush.ahara_shakti", "Ahara Shakti"), ("ayush.vyayama_shakti", "Vyayama Shakti"),
            ("ayush.vaya", "Vaya"), ("ayush.agni", "Agni"), ("ayush.koshtha", "Koshtha"),
        ]:
            if _get(session, slot):
                ayush.append(f"{label}: {term(session.slots[slot])}")
        add(
            "ayush",
            "Dashavidha Pariksha",
            ayush,
            note=(
                "Abbreviated screen based on classical descriptions, not the CCRAS "
                "standardized Prakriti Assessment Scale. Sara, Samhanana and Pramana are "
                "patient-reported, not examination findings. Please confirm."
            ),
        )

        ahara = []
        for slot, label in [
            ("ahara.meal_regularity", "Meals"), ("ahara.rasa_preference", "Predominant rasa"),
            ("ahara.water_intake", "Water intake"), ("vihara.activity", "Activity"),
            ("vihara.sleep_pattern", "Sleep pattern"),
        ]:
            if _get(session, slot):
                ahara.append(f"{label}: {term(session.slots[slot])}")
        if _get(session, "vihara.stress") is not None:
            ahara.append(f"Reported stress: {session.slots['vihara.stress']}/10")
        add("ahara", "Ahara-Vihara", ahara)

    # 9 — Prior investigations
    docs_lines: list[str] = []
    docs_note = None
    if timeline and timeline.get("documents"):
        for doc in timeline["documents"]:
            when = doc["date"] or "date not readable"
            head = f"{when} — {doc['kind'].replace('_', ' ')}"
            if doc["diagnoses"]:
                head += f": {', '.join(doc['diagnoses'])}"
            docs_lines.append(head)
            for med in doc["medications"]:
                dose = " ".join(filter(None, [med.get("dose"), med.get("frequency")]))
                docs_lines.append(f"    {med['name']}{(' — ' + dose) if dose else ''}")
        for abn in timeline.get("abnormal_values", []):
            docs_lines.append(
                f"    ABNORMAL: {abn['analyte']} {abn['value']} {abn['unit'] or ''} "
                f"({abn['direction']}, ref {abn['ref_low']}-{abn['ref_high']})"
            )
        if timeline.get("interactions"):
            docs_note = "Interaction screening only — not a complete interaction check."
    elif session.slots.get("docs.has_papers") is False:
        docs_lines.append("Patient reported no prior documents")
    add("docs", "Prior investigations", docs_lines, note=docs_note)

    cov = coverage(ont, session)
    return {
        "session_id": session.id,
        "status": session.status,
        "generated_from": how,
        "patient": {
            "age_band": term(session.slots.get("identity.age_band")) if session.slots.get("identity.age_band") else None,
            "sex": term(session.slots.get("identity.sex")) if session.slots.get("identity.sex") else None,
            "respondent": session.slots.get("identity.respondent", "self"),
            "language": session.language,
        },
        "proxy_note": _proxy_note(session),
        "red_flag": session.red_flag,
        "sections": sections,
        "coverage": cov,
        "interactions": (timeline or {}).get("interactions", []),
        "abnormal_values": (timeline or {}).get("abnormal_values", []),
        "audit": session.audit,
        "elapsed_s": round(session.elapsed_s, 1),
        "budget_s": session.budget_s,
        "disclaimer": (
            "This is a patient-reported history captured before consultation. "
            "It contains no diagnosis and no clinical interpretation. "
            "Please verify, amend or reject before saving."
        ),
    }
